Create namespace on helm install
The [docs]() state that the helm installation will also create the host
namespace if it does not already exist.

When I ran this, the host namespace was not automatically created and I was
actually returned an error due to `Error: create: failed to create: namespaces
"host-namespace-1" not found`.

When I added the `--create-namespace` flag to the CLI call everything worked
as expected.

<details>
  <summary><Full log outputs of both the error and the working code here 👇</summary>

  ```console
  [22:00:16] (⎈ |kind-vc:default) [~/dev/tmp/vcluster-test]
  $ cat vcluster.yaml
  vcluster:
    image: rancher/k3s:v1.23.5-k3s1    # Choose k3s version

  [22:00:23] (⎈ |kind-vc:default) [~/dev/tmp/vcluster-test]
  $ helm upgrade --install my-vcluster vcluster \
    --values vcluster.yaml \
    --repo https://charts.loft.sh \
    --namespace host-namespace-1 \
    --repository-config=''
  Release "my-vcluster" does not exist. Installing it now.
  Error: create: failed to create: namespaces "host-namespace-1" not found
  [22:00:32] (⎈ |kind-vc:default) [~/dev/tmp/vcluster-test]
  $ helm upgrade --install my-vcluster vcluster \
    --values vcluster.yaml \
    --repo https://charts.loft.sh \
    --namespace host-namespace-1 \
    --repository-config='' \
  > --create-namespace
  Release "my-vcluster" does not exist. Installing it now.
  NAME: my-vcluster
  LAST DEPLOYED: Wed Nov  9 22:01:03 2022
  NAMESPACE: host-namespace-1
  STATUS: deployed
  REVISION: 1
  TEST SUITE: None
  NOTES:
  Thank you for installing vcluster.

  Your vcluster is named my-vcluster in namespace host-namespace-1.

  To connect to the vcluster, use vcluster CLI (https://www.vcluster.com/docs/getting-started/setup):
    $ vcluster connect my-vcluster -n host-namespace-1
    $ vcluster connect my-vcluster -n host-namespace-1 -- kubectl get ns

  For more information, please take a look at the vcluster docs at https://www.vcluster.com/docs
  ```

</details>